name: Test with Buck
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-20.04 # Not latest, because python3.6 is not available on latest
                          # https://github.com/actions/setup-python/issues/544
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        # We use tags to determine version, so fetch them
        fetch-depth: 0
        fetch-tags: true
    - name: Perform tests
      id: test
      uses: SandakovMM/build-with-buck@v3
      with:
        command: test
        target: --all
